# Generated by Django 4.0.4 on 2022-07-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '__first__'),
        ('checkout', '__first__'),
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.shippingaddress')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.delivery')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
