# Generated by Django 4.0.4 on 2022-07-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='customer',
        ),
    ]
